version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - "8080:3000"
    volumes:
      - /app/node_modules
      - .:/app
    stdin_open: true
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    volumes:
      - /app/node_modules
      - .:/app
    stdin_open: true
    command: ["npm", "run", "test"]
